name: borsar
channels:
- conda-forge
dependencies:
# MNE-Python 1.4 is tested in CI with this environment.  It does not support
# the Python 3.13 environment used by the current-MNE jobs.
- python=3.11
- pip
- mkl
- numpy
- scipy
- matplotlib=3.9
- pandas
- xlrd
- scikit-learn
- scikit-image
- h5py
# dev/testing libraries:
- statsmodels
- pytest
- pytest-cov
- psutil
- numpydoc
- flake8
# likely not needed:
- joblib
- pip:
  - h5io
  - pydocstyle
  - codespell
  - sphinx_gallery
  - sphinx_bootstrap_theme
