name: borsar
channels:
- conda-forge
dependencies:
- python=3.13
- pip
- numpy
- scipy
- matplotlib
- pandas
- xlrd
- scikit-learn
- scikit-image
- h5py
# dev/testing libraries:
- statsmodels
- pytest
- pytest-cov
- psutil
- numpydoc
- flake8
# likely not needed:
- joblib
- pip:
  - h5io
  - pydocstyle
  - codespell
  - sphinx_gallery
  - sphinx_bootstrap_theme
