[workspace]
authors = ["Mikołaj Magnuski <mmagnuski@swps.edu.pl>"]
channels = ["conda-forge"]
name = "borsar-ci"
platforms = ["linux-64"]
version = "0.2.0"

[dependencies]
python = "3.11.*"
pip = "*"
numpy = "<2"
scipy = "<1.17"
matplotlib = "3.9.*"
pandas = "*"
xlrd = "*"
scikit-learn = "*"
scikit-image = "*"
xarray = "*"
h5py = "*"
statsmodels = "*"
pytest = "*"
pytest-cov = "*"
psutil = "*"
numpydoc = "*"
flake8 = "*"
joblib = "*"
mne = "1.4.*"
h5io = "*"
tqdm = "*"
numba = "*"

[pypi-dependencies]
borsar = { path = ".", editable = true }
