version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    environment:
      USE_NUMBA: "yes"
    steps:
      - checkout
      - run:
          name: Create conda env
          command: |
            conda create -n test_env python=3.9 matplotlib scipy -y
            source activate test_env
            if [ "${USE_NUMBA}" == "yes" ]; then
              conda install numba;
            fi
            conda install scikit-image
            pip install mne
            pip install codecov tqdm
      - run:
          name: Run tests
          command: |
            ls -al
            echo '^^^The files in your repo^^^'