version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    environment:
      USE_NUMBA: "yes"
    steps:
      - checkout
      - run:
          name: Create conda env
          command: |
            conda create -n test_env python=3.9 matplotlib scipy scikit-image -y
            source activate test_env
            if [ "${USE_NUMBA}" == "yes" ]; then
              conda install numba;
            fi
            pip install mne
            pip install codecov tqdm
      - run:
          name: Run tests
          command: |
            pytest --cov=borsar borsar/
      - run:
          name: Update coverage
          command: |
            codecov