version: 2.1
orbs:
  codecov: codecov/codecov@3.3.0
jobs:
  build:
    docker:
      - image: condaforge/mambaforge:latest
    parameters:
      mne_version:
        type: string
        default: "current"
      use_numba:
        type: string
        default: "no"
    steps:
      - checkout
      - run:
          name: Create conda env
          command: |
            mamba env create -f environment.yml
            source activate borsar
            if [ << parameters.use_numba >> == "yes" ]; then
              mamba install numba -y;
            fi
            if [ << parameters.mne_version >> == "current" ]; then
              pip install mne
            else
              pip install mne==<< parameters.mne_version >>;
            fi
            if [ "<< parameters.mne_version >>" == "1.4.0" ]; then
              mamba install "matplotlib==3.3.4" -y
            fi
            pip install tqdm
            hash -r pytest
      - run:
          name: Run tests
          command: |
            apt update
            apt-get -y install curl gnupg
            source activate borsar
            python -m pytest --cov=borsar borsar/ \
                             --cov-report xml:"./coverage.xml"
      - codecov/upload

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              use_numba: ["yes", "no"]
              mne_version: ["current", "1.8.0", "1.4.0"]
