version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/conda-ci-linux-64-python3.9
    parameters:
      mne_version:
        type: string
        default: "current"
      use_numba:
        type: string
        default: "no"
    steps:
      - checkout
      - run:
          name: Create conda env
          command: |
            conda env create -f environment.yml
            source activate borsar
            if [ << parameters.use_numba >> == "yes" ]; then
              conda install numba -y;
            fi
            if [ << parameters.mne_version >> == "current" ]; then
              pip install mne
            else
              pip install mne==<< parameters.mne_version >>;
            fi
            pip install codecov tqdm
            hash -r pytest
      - run:
          name: Run tests
          command: |
            source activate borsar
            python -m pytest --cov=borsar borsar/
      - run:
          name: Update coverage
          command: |
            source activate borsar
            codecov
workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              use_numba: ["yes", "no"]
              mne_version: ["current", "0.23.4", "0.21.2"]
